# **E-Commerce Data**

Baixar:

In [ ]:
import pandas as pd
import os

path = "/kaggle/input/ecommerce-data"

# Veja o nome exato do arquivo
print(os.listdir(path))
# Deve mostrar algo como: 'data.csv'
arquivo = "data.csv"  # troque se o nome for diferente

# Leia usando outra codificação
df = pd.read_csv(os.path.join(path, arquivo), encoding="latin1")

# Mostre as primeiras linhas
print(df.head())

['data.csv']
  InvoiceNo StockCode                          Description  Quantity  \
0    536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6
1    536365     71053                  WHITE METAL LANTERN         6
2    536365    84406B       CREAM CUPID HEARTS COAT HANGER         8
3    536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6
4    536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6

      InvoiceDate  UnitPrice  CustomerID         Country
0  12/1/2010 8:26       2.55     17850.0  United Kingdom
1  12/1/2010 8:26       3.39     17850.0  United Kingdom
2  12/1/2010 8:26       2.75     17850.0  United Kingdom
3  12/1/2010 8:26       3.39     17850.0  United Kingdom
4  12/1/2010 8:26       3.39     17850.0  United Kingdom

Analisar:

In [ ]:
df.info()       # tipos de cada coluna
df.describe()   # estatísticas numéricas
df.isnull().sum()  # valores nulos por coluna

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  object
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 33.1+ MB

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [ ]:
df.head(10)     # primeiras 10 linhas
df.sample(5)    # 5 linhas aleatórias

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
523779,580520,21914,BLUE HARMONICA IN BOX,1,12/4/2011 14:55,1.25,13521.0,United Kingdom
482173,577411,22659,LUNCH BOX I LOVE LONDON,2,11/20/2011 11:00,1.95,17387.0,United Kingdom
352930,567702,23630,SET 10 CARDS HANGING BAUBLES 17080,1,9/22/2011 9:38,2.99,15810.0,United Kingdom
475036,576860,23391,I LOVE LONDON MINI BACKPACK,6,11/16/2011 15:58,4.15,17602.0,United Kingdom
153493,549748,21843,RED RETROSPOT CAKE STAND,2,4/12/2011 10:42,10.95,17428.0,United Kingdom

In [ ]:
(df['Quantity'] * df['UnitPrice']).sum() #Receita total

np.float64(9747747.933999998)

In [ ]:
df[df['Country'] == 'France'] #Filtrar por país

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
26,536370,22728,ALARM CLOCK BAKELIKE PINK,24,12/1/2010 8:45,3.75,12583.0,France
27,536370,22727,ALARM CLOCK BAKELIKE RED,24,12/1/2010 8:45,3.75,12583.0,France
28,536370,22726,ALARM CLOCK BAKELIKE GREEN,12,12/1/2010 8:45,3.75,12583.0,France
29,536370,21724,PANDA AND BUNNIES STICKER SHEET,12,12/1/2010 8:45,0.85,12583.0,France
30,536370,21883,STARS GIFT TAPE,24,12/1/2010 8:45,0.65,12583.0,France
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/9/2011 12:50,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/9/2011 12:50,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/9/2011 12:50,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/2011 12:50,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/9/2011 12:50,4.95,12680.0,France

In [ ]:
df.groupby('Description')['Quantity'].sum().sort_values(ascending=False).head(10) #Top produtos

Description
WORLD WAR 2 GLIDERS ASSTD DESIGNS     53847
JUMBO BAG RED RETROSPOT               47363
ASSORTED COLOUR BIRD ORNAMENT         36381
POPCORN HOLDER                        36334
PACK OF 72 RETROSPOT CAKE CASES       36039
WHITE HANGING HEART T-LIGHT HOLDER    35317
RABBIT NIGHT LIGHT                    30680
MINI PAINT SET VINTAGE                26437
PACK OF 12 LONDON TISSUES             26315
PACK OF 60 PINK PAISLEY CAKE CASES    24753
Name: Quantity, dtype: int64

# **Students Performance in Exams**

Baixar:

In [ ]:
import kagglehub
import os
import pandas as pd

# 1️⃣ Baixar a versão mais recente do dataset
path = kagglehub.dataset_download("spscientist/students-performance-in-exams")
print("Pasta do dataset:", path)

# 2️⃣ Listar os arquivos disponíveis (é só um CSV)
print(os.listdir(path))
# Deve mostrar algo como: 'StudentsPerformance.csv'

# 3️⃣ Carregar o CSV em um DataFrame
arquivo = "StudentsPerformance.csv"  # confirme o nome exato
df = pd.read_csv(os.path.join(path, arquivo))

# 4️⃣ Conferir as primeiras linhas
print(df.head())

Using Colab cache for faster access to the 'students-performance-in-exams' dataset.
Pasta do dataset: /kaggle/input/students-performance-in-exams
['StudentsPerformance.csv']
   gender race/ethnicity parental level of education         lunch  \
0  female        group B           bachelor's degree      standard
1  female        group C                some college      standard
2  female        group B             master's degree      standard
3    male        group A          associate's degree  free/reduced
4    male        group C                some college      standard

  test preparation course  math score  reading score  writing score
0                    none          72             72             74
1               completed          69             90             88
2                    none          90             95             93
3                    none          47             57             44
4                    none          76             78             75

Analisar:

In [ ]:
df.info()       # tipos de cada coluna
df.describe()   # estatísticas numéricas
df.isnull().sum()  # valores nulos por coluna

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

In [ ]:
df.head(10)     # primeiras 10 linhas
df.sample(5)    # 5 linhas aleatórias

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
106,female,group D,master's degree,standard,none,87,100,100
831,female,group C,bachelor's degree,free/reduced,completed,74,86,89
700,female,group E,bachelor's degree,standard,completed,79,81,82
415,male,group E,high school,standard,none,84,73,69
133,female,group C,some college,standard,completed,75,81,84

In [ ]:
df[['math score','reading score','writing score']].mean() #Médias gerais

math score       66.089
reading score    69.169
writing score    68.054
dtype: float64

In [ ]:
df.groupby('gender')[['math score','reading score','writing score']].mean() #Médias por gênero

        math score  reading score  writing score
gender
female   63.633205      72.608108      72.467181
male     68.728216      65.473029      63.311203

In [ ]:
df[['reading score','writing score']].corr() #Relação leitura x escrita

               reading score  writing score
reading score       1.000000       0.954598
writing score       0.954598       1.000000

# **Walmart Dataset**

Baixar:

In [ ]:
import kagglehub
import os
import pandas as pd

# 1️⃣ Baixar a versão mais recente do dataset
path = kagglehub.dataset_download("yasserh/walmart-dataset")
print("Pasta do dataset:", path)

# 2️⃣ Listar os arquivos disponíveis (é só um CSV)
print(os.listdir(path))
# Deve mostrar algo como: ['Walmart.csv']

# 3️⃣ Carregar o CSV em um DataFrame
arquivo = "Walmart.csv"  # confirme o nome exato
df = pd.read_csv(os.path.join(path, arquivo))

# 4️⃣ Conferir as primeiras linhas
print(df.head())

Using Colab cache for faster access to the 'walmart-dataset' dataset.
Pasta do dataset: /kaggle/input/walmart-dataset
['Walmart.csv']
   Store        Date  Weekly_Sales  Holiday_Flag  Temperature  Fuel_Price  \
0      1  05-02-2010    1643690.90             0        42.31       2.572
1      1  12-02-2010    1641957.44             1        38.51       2.548
2      1  19-02-2010    1611968.17             0        39.93       2.514
3      1  26-02-2010    1409727.59             0        46.63       2.561
4      1  05-03-2010    1554806.68             0        46.50       2.625

          CPI  Unemployment
0  211.096358         8.106
1  211.242170         8.106
2  211.289143         8.106
3  211.319643         8.106
4  211.350143         8.106

Analisar:

In [ ]:
df.info()       # tipos de cada coluna
df.describe()   # estatísticas numéricas
df.isnull().sum()  # valores nulos por coluna

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6435 entries, 0 to 6434
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Store         6435 non-null   int64
 1   Date          6435 non-null   object
 2   Weekly_Sales  6435 non-null   float64
 3   Holiday_Flag  6435 non-null   int64
 4   Temperature   6435 non-null   float64
 5   Fuel_Price    6435 non-null   float64
 6   CPI           6435 non-null   float64
 7   Unemployment  6435 non-null   float64
dtypes: float64(5), int64(2), object(1)
memory usage: 402.3+ KB

Store           0
Date            0
Weekly_Sales    0
Holiday_Flag    0
Temperature     0
Fuel_Price      0
CPI             0
Unemployment    0
dtype: int64

In [ ]:
df.head(10)     # primeiras 10 linhas
df.sample(5)    # 5 linhas aleatórias

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment
5728,41,02-04-2010,1168826.39,0,41.31,2.725,189.704822,7.363
5900,42,22-10-2010,522467.51,0,68.12,3.014,126.381548,9.003
6215,44,13-05-2011,307095.31,0,52.40,3.770,129.089000,6.906
6029,43,16-07-2010,696844.36,0,84.17,2.623,203.053855,9.816
6357,45,06-05-2011,810150.64,0,58.21,4.046,185.937438,8.521

In [ ]:
df['Weekly_Sales'].sum() # Receita total

np.float64(6737218987.11)

In [ ]:
df.groupby('Store')['Weekly_Sales'].mean().sort_values(ascending=False) # Receita média por loja

Store
20    2.107677e+06
4     2.094713e+06
14    2.020978e+06
13    2.003620e+06
2     1.925751e+06
10    1.899425e+06
27    1.775216e+06
6     1.564728e+06
1     1.555264e+06
39    1.450668e+06
19    1.444999e+06
31    1.395901e+06
23    1.389864e+06
24    1.356755e+06
11    1.356383e+06
28    1.323522e+06
41    1.268125e+06
32    1.166568e+06
18    1.084718e+06
22    1.028501e+06
12    1.009002e+06
26    1.002912e+06
34    9.667816e+05
40    9.641280e+05
35    9.197250e+05
8     9.087495e+05
17    8.935814e+05
45    7.859814e+05
21    7.560691e+05
25    7.067215e+05
43    6.333247e+05
15    6.233125e+05
7     5.706173e+05
42    5.564039e+05
9     5.439806e+05
29    5.394514e+05
16    5.192477e+05
37    5.189003e+05
30    4.385796e+05
3     4.027044e+05
38    3.857317e+05
36    3.735120e+05
5     3.180118e+05
44    3.027489e+05
33    2.598617e+05
Name: Weekly_Sales, dtype: float64